### ISSUE TITLE
📌 Switch mocking library from golang/mock to go.uber.org/mock

### ISSUE THREAD

**Issue by ccamel** [axone-protocol/axoned#770]
The current mocking library we use in this repo, [golang/mock](https://github.com/golang/mock), has been archived as of June 27, 2023. Following the notice in the repository, I suggest switching to [go.uber.org/mock](https://github.com/uber-go/mock), which is a maintained fork.

**Comment by elprogramadorgt** [comment]
Hello, I would like to help for this issue

**Comment by ccamel** [comment]
> Hello, I would like to help for this issue

Appreciate the offer @elprogramadorgt! 😃 Feel free to dive in and contribute!
Let us know if you have any questions or need guidance.

**Comment by elprogramadorgt** [comment]
Thanks @ccamel, I made all the changes, how can I test it? to see if it's working?

I already run the commands 
```go
make install
make build-go
./target/dist/axoned 
```

and got no errors, but I would like to confirm before I make my PR

**Comment by ccamel** [comment]
Awesome @elprogramadorgt! To double-check that everything is working smoothly, you can run the tests with:

```sh
make test-go
```

Also, just a quick reminder to follow the [Conventional Commits](https://github.com/okp4/team-wiki/blob/f8b4c9d9b5b554014a84edf5a1372daca3f0891d/docs/dev/naming-rules.md) for your commit messages and make sure your commits are signed. 

Thanks for all the effort, this is looking great!

**Comment by elprogramadorgt** [comment]
Thanks @ccamel, I have everything but apparently I don't have access. This is the error

remote: Permission to axone-protocol/axoned.git denied to elprogramadorgt.
fatal: unable to access 'https://github.com/axone-protocol/axoned.git/': The requested URL returned error: 403

**Comment by ccamel** [comment]
@elprogramadorgt Oh, I see. You don’t have direct push access to the repository, so you’ll need to _fork_ the project, create a new branch on your fork, and then push your changes there. After that, you can open a pull request  to merge your branch into our repo. For more details, you can check out this guide: [Contributing to a project on GitHub](https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project). 

And of course, feel free to reach out if you need any help!

**Comment by elprogramadorgt** [comment]
@ccamel  I just have a question on the Makefile, there is this command 
```make
@go install github.com/golang/mock/mockgen@v1.6.0
```
I don't know how it should be the change for the new library.

because when I run that with the new library I have this message.
```sh
go install go.uber.org/mock@v0.5.0 
go: go.uber.org/mock@v0.5.0: module go.uber.org/mock@v0.5.0 found, but does not contain package go.uber.org/mock
```
that's the last part I have before making my PR, 

I submitted 2 but I have some issues that's why I cancel them so I will make a clean PR now

**Comment by elprogramadorgt** [comment]
Hey @ccamel, good news, the PR is ready, sorry for the delay,  I had some trouble with some naming conventions but i'ts done! It' was fun, I will see if there something else I can help :) if you have something let me know. and if there is something wrong with my PR also let me know :)
