### ISSUE TITLE
👷🏼 Upgrade golangci-lint to the latest version

### ISSUE THREAD

**Issue by ccamel** [axone-protocol/axoned#775]
## Purpose

The current version of [golangci-lint](https://golangci-lint.run/) used in this repo is quite old (`v1.56`). It would be beneficial to update to the [latest available version](https://github.com/golangci/golangci-lint/releases) to take advantage of the latest improvements, bug fixes, and features.

## Suggested action:

- Update [golangci-lint](https://github.com/golangci/golangci-lint/releases) to the latest stable version.
- Update the codebase if the linter requires any changes.

**Comment by dangogh** [comment]
question: a number of gosec:G115 warnings (potential int conversion overflow).  Should be able to safely ignore these, but opinion on how this project wants to handle them?

**Comment by ccamel** [comment]
@dangogh That’s a great question.  I agree that not all G115 warnings can be properly addressed (for now), and it makes sense to disable them on a case-by-case basis. From what I can see, you’ve already handled this appropriately in the commit [f903d5f](https://github.com/axone-protocol/axoned/pull/776/commits/f903d5fba7470539675fb56bc8afafe89e516ace), so this approach looks good to me. :+1:
